In [11]:
n=int(input('enter a num of students'))
sem=int(input('enter a num of sem'))
sub=int(input('enter a number of subjects'))
student=[]
for a in range(n):
    semlist=[]
    for b in range(sem):
        marklist=[]
        for c in range(sub):
            mark=int(input(f'enter a student {a} and sem {b} and subject{c}='))
            marklist.append(mark)
        semlist.append(marklist)
        print(marklist)
        print(semlist)
    studentlist.append(semlist)
    print(studentlist)

enter a num of students 2
enter a num of sem 3
enter a number of subjects 2
enter a student 0 and sem 0 and subject0= 34
enter a student 0 and sem 0 and subject1= 34


[34, 34]
[[34, 34]]


enter a student 0 and sem 1 and subject0= 45
enter a student 0 and sem 1 and subject1= 67


[45, 67]
[[34, 34], [45, 67]]


enter a student 0 and sem 2 and subject0= 76
enter a student 0 and sem 2 and subject1= 45


[76, 45]
[[34, 34], [45, 67], [76, 45]]


NameError: name 'studentlist' is not defined

In [1]:
import numpy as np
j=np.array(studentlist) #print(np.array(studentlist))
print(j)

NameError: name 'studentlist' is not defined

In [23]:
print(np.arange(27))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [33]:
print(np.linspace(0,10,5)) #printing the equal separation of ending number in random

[ 0.   2.5  5.   7.5 10. ]


In [41]:
print(np.linspace(0,10,6))

[ 0.  2.  4.  6.  8. 10.]


In [45]:
print(np.arange(0,10,1.5))

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [49]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [55]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [67]:
print(np.ones((5,2,3))) # (row,subrows,column) zeros and ones 

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [79]:
print(np.full((5,2,3),17)) #used to fill selective num to rows and columns

[[[17 17 17]
  [17 17 17]]

 [[17 17 17]
  [17 17 17]]

 [[17 17 17]
  [17 17 17]]

 [[17 17 17]
  [17 17 17]]

 [[17 17 17]
  [17 17 17]]]


In [89]:
print(np.random.rand(4,3,2)) #print random values inside the matrix

[[[0.05875289 0.53069407]
  [0.27473637 0.28412824]
  [0.33680692 0.28989764]]

 [[0.11000735 0.98441627]
  [0.1110038  0.82035165]
  [0.61237131 0.38853485]]

 [[0.61172388 0.50322543]
  [0.96811639 0.9868459 ]
  [0.26988305 0.07787577]]

 [[0.0318961  0.77154063]
  [0.48381825 0.259706  ]
  [0.4560609  0.39047661]]]


In [93]:
print(np.random.randint(0,7,size=(10,5)))

[[3 1 2 0 3]
 [2 3 0 4 5]
 [0 1 1 4 1]
 [1 0 5 0 0]
 [1 5 6 2 4]
 [6 2 1 0 3]
 [2 2 2 6 2]
 [0 4 5 2 3]
 [1 3 1 2 5]
 [6 2 2 0 2]]


In [95]:
print(np.random.randint(0,7,size=(10,3,5)))

[[[3 3 4 4 6]
  [5 2 2 3 4]
  [6 2 0 0 6]]

 [[1 2 3 4 4]
  [0 0 4 5 4]
  [6 1 1 2 5]]

 [[2 5 3 6 0]
  [5 1 5 5 6]
  [1 6 1 0 2]]

 [[2 3 6 0 2]
  [1 0 5 5 4]
  [3 0 3 1 2]]

 [[1 3 3 0 6]
  [1 6 0 6 5]
  [0 5 1 4 6]]

 [[5 6 4 2 2]
  [2 3 0 1 4]
  [6 5 2 4 3]]

 [[3 4 6 6 2]
  [3 0 2 2 1]
  [3 6 3 0 6]]

 [[3 6 4 2 5]
  [6 1 2 4 6]
  [3 0 6 0 4]]

 [[2 1 6 1 4]
  [6 0 3 4 0]
  [4 1 2 4 0]]

 [[4 3 3 2 5]
  [1 2 3 3 1]
  [4 5 4 1 0]]]


In [13]:
import numpy as np
l=[1,2,3,4]
a=np.array(l)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[1 2 3 4]
int32
1
(4,)
4


In [19]:
l1=[[2,3,5],[4,5,8],[5,8,9]]
a=np.array(l1)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[[2 3 5]
 [4 5 8]
 [5 8 9]]
int32
2
(3, 3)
9


In [23]:
l2=[[[2,3,5],[4,5,8]],[[5,8,9],[6,7,9]]]
a=np.array(l2)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[[[2 3 5]
  [4 5 8]]

 [[5 8 9]
  [6 7 9]]]
int32
3
(2, 2, 3)
12


In [27]:
a=[48,2,4,5,6,78,5]
o=[]
for i in range(len(a)):
    o.append(a[i]+1)
print(o)

[49, 3, 5, 6, 7, 79, 6]


In [41]:
s=np.array(a)
print(s+1)

[49  3  5  6  7 79  6]


In [78]:
#3dimension array
l=[[1,2],[2,3],[9,8]]
print(l)
a=np.array(l)
print(a)
print(a.sum())#adding overall matrix
print(a.min())
print(a.mean())
print(a.max())
print(a.std()) 
print(a.cumsum()) #adding in series one by one
print(a.sum(axis=0)) #adding column in matrix
print(a.sum(axis=1)) #adding row in matrix
print(a.mean(axis=0))
print(a.min(axis=0))

[[1, 2], [2, 3], [9, 8]]
[[1 2]
 [2 3]
 [9 8]]
25
1
4.166666666666667
9
3.131382371342656
[ 1  3  5  8 17 25]
[12 13]
[ 3  5 17]
[4.         4.33333333]
[1 2]


In [74]:
#1 dimension array
l=[2,3,4,5,6]
print(l)
a=np.array(l)
print(a)
print(a.sum())
print(a.min())
print(a.mean())
print(a.max())
print(a.std()) 
print(a.cumsum())
print(a.sum(axis=0))


[2, 3, 4, 5, 6]
[2 3 4 5 6]
20
2
4.0
6
1.4142135623730951
[ 2  5  9 14 20]
20
